# Generated by Django 6.1.1 on 2026-09-13 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('raw_text', models.TextField()),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('links', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('insight', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('ssd', 'SSD/NAND'), ('automotive', '자동차 SW')], max_length=20)),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='digest.dailydigest')),
            ],
            options={
                'ordering': ['digest__date'],
            },
        ),
        migrations.CreateModel(
            name='LearningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_items', to='digest.dailydigest')),
            ],
            options={
                'ordering': ['digest__date'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200)),
                ('meaning', models.TextField()),
                ('relevance', models.TextField(blank=True)),
                ('familiarity', models.CharField(choices=[('new', '처음 봄'), ('familiar', '익숙함'), ('mastered', '설명 가능')], default='new', max_length=20)),
                ('first_seen_digest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms', to='digest.dailydigest')),
            ],
            options={
                'ordering': ['term'],
                'unique_together': {('term',)},
            },
        ),
    ]
