# Generated by Django 4.2.30 on 2026-09-14 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0002_alter_article_id_alter_dailydigest_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='appeared_in',
            field=models.ManyToManyField(blank=True, related_name='mentioned_terms', to='digest.dailydigest'),
        ),
        migrations.AlterField(
            model_name='term',
            name='first_seen_digest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_seen_terms', to='digest.dailydigest'),
        ),
    ]
