# Generated by Django 4.2.30 on 2026-09-14 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digest', '0004_alter_article_id_alter_dailydigest_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='familiarity',
        ),
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiarity', models.CharField(choices=[('new', '몰랐음'), ('familiar', '애매함'), ('mastered', '알았음')], default='new', max_length=20)),
                ('interval_days', models.PositiveIntegerField(default=1)),
                ('next_review_date', models.DateField()),
                ('last_reviewed_at', models.DateTimeField(auto_now=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_records', to='digest.term')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_review_date'],
                'unique_together': {('user', 'term')},
            },
        ),
    ]
