# Generated by Django 4.2.30 on 2026-09-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0008_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='digest.tag'),
        ),
    ]
