# Generated by Django 4.2.30 on 2026-09-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0009_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningitem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='digest.tag'),
        ),
    ]
