# Generated by Django 4.2.30 on 2026-09-28 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0010_learningitem_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='tag',
            name='lesson_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tag',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_chapters', to='digest.tag'),
        ),
        migrations.AddField(
            model_name='term',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='terms', to='digest.tag'),
        ),
    ]
