# Generated by Django 4.2.30 on 2026-10-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0012_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='deep_dive',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningitem',
            name='deep_dive',
            field=models.TextField(blank=True),
        ),
    ]
