# Generated by Django 4.2.30 on 2026-10-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0013_deep_dive'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningitem',
            name='source_text',
            field=models.TextField(blank=True),
        ),
    ]
